// Generated by CoffeeScript 1.3.3
(function() {
  var PubSub;

  PubSub = (function() {

    function PubSub(events) {
      this.events = events != null ? events : [];
    }

    PubSub.prototype.subscribe = function(name, func) {
      if (this.events[name]) {
        return this.events[name].push(func);
      } else {
        return this.events[name] = [func];
      }
    };

    PubSub.prototype.publish = function(name) {
      var event, _i, _len, _ref, _results;
      if (this.events[name]) {
        _ref = this.events[name];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          event = _ref[_i];
          _results.push(event());
        }
        return _results;
      }
    };

    PubSub.prototype.unsubscribe = function(name) {
      return delete this.events[name];
    };

    return PubSub;

  })();

}).call(this);
